import Head from "next/head";
import axios from "axios";
// import { Inter } from "@next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export default function Home({ videos }) {
    console.log(videos);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1 className="text-3xl font-bold underline">Hello world!</h1>
            </main>
        </>
    );
}

export const getServerSideProps = async () => {
    const response = await axios.get(`http://localhost:3000/api/post`);
    const { data } = response;

    console.log(response.data);

    return {
        props: {
            videos: data
        }
    }
}
